### ISSUE TITLE
How to use node.js to node.js

### ISSUE THREAD

**Issue by 0xLevin** [teambition/snapper-consumer#4]
How to use node.js to node.js

**Comment by zensh** [comment]
https://github.com/teambition/snapper-core/blob/master/test/index.js

all tests run in node.js

**Comment by 0xLevin** [comment]
Thank you, I want to use it to the message center, then push notification to the other node.js applications, I want to see the document, and try it

**Comment by zensh** [comment]
It is not good for your case. You should use message queue, such as zeromq.
